# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pmacs-rails_sql_views 0.12.4 ruby lib

Gem::Specification.new do |s|
  s.name = "pmacs-rails_sql_views".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Charles Treatman".freeze, "Anthony Eden".freeze, "Greg Barendt".freeze, "Raj Iyengar".freeze]
  s.date = "2025-01-09"
  s.description = "Adds support for using SQL views within ActiveRecord".freeze
  s.email = ["barendt@mail.med.upenn.edu".freeze, "rgi@mail.med.upenn.edu".freeze]
  s.extra_rdoc_files = [
    "CHANGELOG",
    "LICENSE",
    "README",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "README",
    "Rakefile",
    "lib/active_record/view.rb",
    "lib/pmacs-rails_sql_views.rb",
    "lib/rails_sql_views/connection_adapters/abstract/schema_definitions.rb",
    "lib/rails_sql_views/connection_adapters/abstract/schema_statements.rb",
    "lib/rails_sql_views/connection_adapters/abstract_adapter.rb",
    "lib/rails_sql_views/connection_adapters/mysql_adapter.rb",
    "lib/rails_sql_views/connection_adapters/oci_adapter.rb",
    "lib/rails_sql_views/connection_adapters/oracle_adapter.rb",
    "lib/rails_sql_views/connection_adapters/oracleenhanced_adapter.rb",
    "lib/rails_sql_views/connection_adapters/postgresql_adapter.rb",
    "lib/rails_sql_views/connection_adapters/sqlite3_adapter.rb",
    "lib/rails_sql_views/connection_adapters/sqlite_adapter.rb",
    "lib/rails_sql_views/connection_adapters/sqlserver_adapter.rb",
    "lib/rails_sql_views/loader.rb",
    "lib/rails_sql_views/migration/command_recorder.rb",
    "lib/rails_sql_views/schema_dumper.rb"
  ]
  s.homepage = "http://github.com/pmacs/rails_sql_views".freeze
  s.rubygems_version = "3.3.27".freeze
  s.summary = "Library which adds SQL Views to ActiveRecord.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<activerecord>.freeze, [">= 8"])
  else
    s.add_dependency(%q<activerecord>.freeze, [">= 8"])
  end
end
